// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSW0fRqKMfdQoWJujOuAisPF-SOeOpl3Q',
    appId: '1:354936711281:web:ebcd5f7cc68f37f68c13d0',
    messagingSenderId: '354936711281',
    projectId: 'camp-live-cloud-c2687',
    authDomain: 'camp-live-cloud-c2687.firebaseapp.com',
    databaseURL: 'https://camp-live-cloud-c2687-default-rtdb.firebaseio.com',
    storageBucket: 'camp-live-cloud-c2687.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4dkIEzNMIgBIf4WADkA2A9mAKcl-anUI',
    appId: '1:354936711281:android:fa61ec53f23ff4cf8c13d0',
    messagingSenderId: '354936711281',
    projectId: 'camp-live-cloud-c2687',
    databaseURL: 'https://camp-live-cloud-c2687-default-rtdb.firebaseio.com',
    storageBucket: 'camp-live-cloud-c2687.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDcfFxmEk81TVpY8VCreAPg1zIWoP006k',
    appId: '1:354936711281:ios:905b24ff4dee1d7f8c13d0',
    messagingSenderId: '354936711281',
    projectId: 'camp-live-cloud-c2687',
    databaseURL: 'https://camp-live-cloud-c2687-default-rtdb.firebaseio.com',
    storageBucket: 'camp-live-cloud-c2687.firebasestorage.app',
    iosBundleId: 'com.example.campLive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDcfFxmEk81TVpY8VCreAPg1zIWoP006k',
    appId: '1:354936711281:ios:905b24ff4dee1d7f8c13d0',
    messagingSenderId: '354936711281',
    projectId: 'camp-live-cloud-c2687',
    databaseURL: 'https://camp-live-cloud-c2687-default-rtdb.firebaseio.com',
    storageBucket: 'camp-live-cloud-c2687.firebasestorage.app',
    iosBundleId: 'com.example.campLive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSW0fRqKMfdQoWJujOuAisPF-SOeOpl3Q',
    appId: '1:354936711281:web:191cdc6933d7c95a8c13d0',
    messagingSenderId: '354936711281',
    projectId: 'camp-live-cloud-c2687',
    authDomain: 'camp-live-cloud-c2687.firebaseapp.com',
    databaseURL: 'https://camp-live-cloud-c2687-default-rtdb.firebaseio.com',
    storageBucket: 'camp-live-cloud-c2687.firebasestorage.app',
  );
}
